// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface CadastroRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CadastroRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nome = 1;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 1;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string cpf = 2;</code>
   * @return The cpf.
   */
  java.lang.String getCpf();
  /**
   * <code>string cpf = 2;</code>
   * @return The bytes for cpf.
   */
  com.google.protobuf.ByteString
      getCpfBytes();

  /**
   * <code>string senha = 3;</code>
   * @return The senha.
   */
  java.lang.String getSenha();
  /**
   * <code>string senha = 3;</code>
   * @return The bytes for senha.
   */
  com.google.protobuf.ByteString
      getSenhaBytes();

  /**
   * <code>int32 tipo = 4;</code>
   * @return The tipo.
   */
  int getTipo();
}
