// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface DepositoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DepositoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numeroDeposito = 1;</code>
   * @return The numeroDeposito.
   */
  int getNumeroDeposito();

  /**
   * <code>double valorDeposito = 2;</code>
   * @return The valorDeposito.
   */
  double getValorDeposito();
}
