// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * Protobuf type {@code ExtratoResponse}
 */
@com.google.protobuf.Generated
public final class ExtratoResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ExtratoResponse)
    ExtratoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExtratoResponse");
  }
  // Use ExtratoResponse.newBuilder() to construct.
  private ExtratoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExtratoResponse() {
    linhas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.ExtratoResponse.class, com.banco.protocolo.ExtratoResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int LINHAS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList linhas_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string linhas = 2;</code>
   * @return A list containing the linhas.
   */
  public com.google.protobuf.ProtocolStringList
      getLinhasList() {
    return linhas_;
  }
  /**
   * <code>repeated string linhas = 2;</code>
   * @return The count of linhas.
   */
  public int getLinhasCount() {
    return linhas_.size();
  }
  /**
   * <code>repeated string linhas = 2;</code>
   * @param index The index of the element to return.
   * @return The linhas at the given index.
   */
  public java.lang.String getLinhas(int index) {
    return linhas_.get(index);
  }
  /**
   * <code>repeated string linhas = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the linhas at the given index.
   */
  public com.google.protobuf.ByteString
      getLinhasBytes(int index) {
    return linhas_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    for (int i = 0; i < linhas_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, linhas_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < linhas_.size(); i++) {
        dataSize += computeStringSizeNoTag(linhas_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinhasList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.ExtratoResponse)) {
      return super.equals(obj);
    }
    com.banco.protocolo.ExtratoResponse other = (com.banco.protocolo.ExtratoResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (!getLinhasList()
        .equals(other.getLinhasList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    if (getLinhasCount() > 0) {
      hash = (37 * hash) + LINHAS_FIELD_NUMBER;
      hash = (53 * hash) + getLinhasList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.ExtratoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.ExtratoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.ExtratoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.ExtratoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.ExtratoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ExtratoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExtratoResponse)
      com.banco.protocolo.ExtratoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.ExtratoResponse.class, com.banco.protocolo.ExtratoResponse.Builder.class);
    }

    // Construct using com.banco.protocolo.ExtratoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      linhas_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ExtratoResponse_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.ExtratoResponse getDefaultInstanceForType() {
      return com.banco.protocolo.ExtratoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.ExtratoResponse build() {
      com.banco.protocolo.ExtratoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.ExtratoResponse buildPartial() {
      com.banco.protocolo.ExtratoResponse result = new com.banco.protocolo.ExtratoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.ExtratoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        linhas_.makeImmutable();
        result.linhas_ = linhas_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.ExtratoResponse) {
        return mergeFrom((com.banco.protocolo.ExtratoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.ExtratoResponse other) {
      if (other == com.banco.protocolo.ExtratoResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.linhas_.isEmpty()) {
        if (linhas_.isEmpty()) {
          linhas_ = other.linhas_;
          bitField0_ |= 0x00000002;
        } else {
          ensureLinhasIsMutable();
          linhas_.addAll(other.linhas_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              ensureLinhasIsMutable();
              linhas_.add(input.readStringRequireUtf8());
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {

      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList linhas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinhasIsMutable() {
      if (!linhas_.isModifiable()) {
        linhas_ = new com.google.protobuf.LazyStringArrayList(linhas_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @return A list containing the linhas.
     */
    public com.google.protobuf.ProtocolStringList
        getLinhasList() {
      linhas_.makeImmutable();
      return linhas_;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @return The count of linhas.
     */
    public int getLinhasCount() {
      return linhas_.size();
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param index The index of the element to return.
     * @return The linhas at the given index.
     */
    public java.lang.String getLinhas(int index) {
      return linhas_.get(index);
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the linhas at the given index.
     */
    public com.google.protobuf.ByteString
        getLinhasBytes(int index) {
      return linhas_.getByteString(index);
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param index The index to set the value at.
     * @param value The linhas to set.
     * @return This builder for chaining.
     */
    public Builder setLinhas(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinhasIsMutable();
      linhas_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param value The linhas to add.
     * @return This builder for chaining.
     */
    public Builder addLinhas(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinhasIsMutable();
      linhas_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param values The linhas to add.
     * @return This builder for chaining.
     */
    public Builder addAllLinhas(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinhasIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, linhas_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinhas() {
      linhas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linhas = 2;</code>
     * @param value The bytes of the linhas to add.
     * @return This builder for chaining.
     */
    public Builder addLinhasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinhasIsMutable();
      linhas_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ExtratoResponse)
  }

  // @@protoc_insertion_point(class_scope:ExtratoResponse)
  private static final com.banco.protocolo.ExtratoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.ExtratoResponse();
  }

  public static com.banco.protocolo.ExtratoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExtratoResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExtratoResponse>() {
    @java.lang.Override
    public ExtratoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExtratoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExtratoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.ExtratoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

