// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface ExtratoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExtratoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated string linhas = 2;</code>
   * @return A list containing the linhas.
   */
  java.util.List<java.lang.String>
      getLinhasList();
  /**
   * <code>repeated string linhas = 2;</code>
   * @return The count of linhas.
   */
  int getLinhasCount();
  /**
   * <code>repeated string linhas = 2;</code>
   * @param index The index of the element to return.
   * @return The linhas at the given index.
   */
  java.lang.String getLinhas(int index);
  /**
   * <code>repeated string linhas = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the linhas at the given index.
   */
  com.google.protobuf.ByteString
      getLinhasBytes(int index);
}
