// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface ExtratoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExtratoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numContaExtrato = 1;</code>
   * @return The numContaExtrato.
   */
  int getNumContaExtrato();
}
