// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * Protobuf type {@code LoginResponse}
 */
@com.google.protobuf.Generated
public final class LoginResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:LoginResponse)
    LoginResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "LoginResponse");
  }
  // Use LoginResponse.newBuilder() to construct.
  private LoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LoginResponse() {
    nomeTitular_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.LoginResponse.class, com.banco.protocolo.LoginResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int TIPO_FIELD_NUMBER = 2;
  private int tipo_ = 0;
  /**
   * <code>int32 tipo = 2;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public int getTipo() {
    return tipo_;
  }

  public static final int NUMEROCONTA_FIELD_NUMBER = 3;
  private int numeroConta_ = 0;
  /**
   * <code>int32 numeroConta = 3;</code>
   * @return The numeroConta.
   */
  @java.lang.Override
  public int getNumeroConta() {
    return numeroConta_;
  }

  public static final int NOMETITULAR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nomeTitular_ = "";
  /**
   * <code>string nomeTitular = 4;</code>
   * @return The nomeTitular.
   */
  @java.lang.Override
  public java.lang.String getNomeTitular() {
    java.lang.Object ref = nomeTitular_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeTitular_ = s;
      return s;
    }
  }
  /**
   * <code>string nomeTitular = 4;</code>
   * @return The bytes for nomeTitular.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeTitularBytes() {
    java.lang.Object ref = nomeTitular_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeTitular_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALDO_FIELD_NUMBER = 5;
  private double saldo_ = 0D;
  /**
   * <code>double saldo = 5;</code>
   * @return The saldo.
   */
  @java.lang.Override
  public double getSaldo() {
    return saldo_;
  }

  public static final int LIMITE_FIELD_NUMBER = 6;
  private double limite_ = 0D;
  /**
   * <code>double limite = 6;</code>
   * @return The limite.
   */
  @java.lang.Override
  public double getLimite() {
    return limite_;
  }

  public static final int RENDIMENTO_FIELD_NUMBER = 7;
  private double rendimento_ = 0D;
  /**
   * <code>double rendimento = 7;</code>
   * @return The rendimento.
   */
  @java.lang.Override
  public double getRendimento() {
    return rendimento_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    if (tipo_ != 0) {
      output.writeInt32(2, tipo_);
    }
    if (numeroConta_ != 0) {
      output.writeInt32(3, numeroConta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeTitular_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, nomeTitular_);
    }
    if (java.lang.Double.doubleToRawLongBits(saldo_) != 0) {
      output.writeDouble(5, saldo_);
    }
    if (java.lang.Double.doubleToRawLongBits(limite_) != 0) {
      output.writeDouble(6, limite_);
    }
    if (java.lang.Double.doubleToRawLongBits(rendimento_) != 0) {
      output.writeDouble(7, rendimento_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    if (tipo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tipo_);
    }
    if (numeroConta_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numeroConta_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeTitular_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, nomeTitular_);
    }
    if (java.lang.Double.doubleToRawLongBits(saldo_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, saldo_);
    }
    if (java.lang.Double.doubleToRawLongBits(limite_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, limite_);
    }
    if (java.lang.Double.doubleToRawLongBits(rendimento_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, rendimento_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.LoginResponse)) {
      return super.equals(obj);
    }
    com.banco.protocolo.LoginResponse other = (com.banco.protocolo.LoginResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (getTipo()
        != other.getTipo()) return false;
    if (getNumeroConta()
        != other.getNumeroConta()) return false;
    if (!getNomeTitular()
        .equals(other.getNomeTitular())) return false;
    if (java.lang.Double.doubleToLongBits(getSaldo())
        != java.lang.Double.doubleToLongBits(
            other.getSaldo())) return false;
    if (java.lang.Double.doubleToLongBits(getLimite())
        != java.lang.Double.doubleToLongBits(
            other.getLimite())) return false;
    if (java.lang.Double.doubleToLongBits(getRendimento())
        != java.lang.Double.doubleToLongBits(
            other.getRendimento())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo();
    hash = (37 * hash) + NUMEROCONTA_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroConta();
    hash = (37 * hash) + NOMETITULAR_FIELD_NUMBER;
    hash = (53 * hash) + getNomeTitular().hashCode();
    hash = (37 * hash) + SALDO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSaldo()));
    hash = (37 * hash) + LIMITE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLimite()));
    hash = (37 * hash) + RENDIMENTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRendimento()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.LoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.LoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.LoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.LoginResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LoginResponse)
      com.banco.protocolo.LoginResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.LoginResponse.class, com.banco.protocolo.LoginResponse.Builder.class);
    }

    // Construct using com.banco.protocolo.LoginResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      tipo_ = 0;
      numeroConta_ = 0;
      nomeTitular_ = "";
      saldo_ = 0D;
      limite_ = 0D;
      rendimento_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginResponse_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.LoginResponse getDefaultInstanceForType() {
      return com.banco.protocolo.LoginResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.LoginResponse build() {
      com.banco.protocolo.LoginResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.LoginResponse buildPartial() {
      com.banco.protocolo.LoginResponse result = new com.banco.protocolo.LoginResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.LoginResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tipo_ = tipo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.numeroConta_ = numeroConta_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nomeTitular_ = nomeTitular_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.saldo_ = saldo_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.limite_ = limite_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.rendimento_ = rendimento_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.LoginResponse) {
        return mergeFrom((com.banco.protocolo.LoginResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.LoginResponse other) {
      if (other == com.banco.protocolo.LoginResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getTipo() != 0) {
        setTipo(other.getTipo());
      }
      if (other.getNumeroConta() != 0) {
        setNumeroConta(other.getNumeroConta());
      }
      if (!other.getNomeTitular().isEmpty()) {
        nomeTitular_ = other.nomeTitular_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getSaldo()) != 0) {
        setSaldo(other.getSaldo());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getLimite()) != 0) {
        setLimite(other.getLimite());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getRendimento()) != 0) {
        setRendimento(other.getRendimento());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              tipo_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              numeroConta_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              nomeTitular_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              saldo_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              limite_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              rendimento_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {

      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private int tipo_ ;
    /**
     * <code>int32 tipo = 2;</code>
     * @return The tipo.
     */
    @java.lang.Override
    public int getTipo() {
      return tipo_;
    }
    /**
     * <code>int32 tipo = 2;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(int value) {

      tipo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tipo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tipo_ = 0;
      onChanged();
      return this;
    }

    private int numeroConta_ ;
    /**
     * <code>int32 numeroConta = 3;</code>
     * @return The numeroConta.
     */
    @java.lang.Override
    public int getNumeroConta() {
      return numeroConta_;
    }
    /**
     * <code>int32 numeroConta = 3;</code>
     * @param value The numeroConta to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroConta(int value) {

      numeroConta_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numeroConta = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroConta() {
      bitField0_ = (bitField0_ & ~0x00000004);
      numeroConta_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nomeTitular_ = "";
    /**
     * <code>string nomeTitular = 4;</code>
     * @return The nomeTitular.
     */
    public java.lang.String getNomeTitular() {
      java.lang.Object ref = nomeTitular_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeTitular_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nomeTitular = 4;</code>
     * @return The bytes for nomeTitular.
     */
    public com.google.protobuf.ByteString
        getNomeTitularBytes() {
      java.lang.Object ref = nomeTitular_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeTitular_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nomeTitular = 4;</code>
     * @param value The nomeTitular to set.
     * @return This builder for chaining.
     */
    public Builder setNomeTitular(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nomeTitular_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string nomeTitular = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNomeTitular() {
      nomeTitular_ = getDefaultInstance().getNomeTitular();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string nomeTitular = 4;</code>
     * @param value The bytes for nomeTitular to set.
     * @return This builder for chaining.
     */
    public Builder setNomeTitularBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nomeTitular_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private double saldo_ ;
    /**
     * <code>double saldo = 5;</code>
     * @return The saldo.
     */
    @java.lang.Override
    public double getSaldo() {
      return saldo_;
    }
    /**
     * <code>double saldo = 5;</code>
     * @param value The saldo to set.
     * @return This builder for chaining.
     */
    public Builder setSaldo(double value) {

      saldo_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double saldo = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSaldo() {
      bitField0_ = (bitField0_ & ~0x00000010);
      saldo_ = 0D;
      onChanged();
      return this;
    }

    private double limite_ ;
    /**
     * <code>double limite = 6;</code>
     * @return The limite.
     */
    @java.lang.Override
    public double getLimite() {
      return limite_;
    }
    /**
     * <code>double limite = 6;</code>
     * @param value The limite to set.
     * @return This builder for chaining.
     */
    public Builder setLimite(double value) {

      limite_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double limite = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimite() {
      bitField0_ = (bitField0_ & ~0x00000020);
      limite_ = 0D;
      onChanged();
      return this;
    }

    private double rendimento_ ;
    /**
     * <code>double rendimento = 7;</code>
     * @return The rendimento.
     */
    @java.lang.Override
    public double getRendimento() {
      return rendimento_;
    }
    /**
     * <code>double rendimento = 7;</code>
     * @param value The rendimento to set.
     * @return This builder for chaining.
     */
    public Builder setRendimento(double value) {

      rendimento_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double rendimento = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRendimento() {
      bitField0_ = (bitField0_ & ~0x00000040);
      rendimento_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:LoginResponse)
  }

  // @@protoc_insertion_point(class_scope:LoginResponse)
  private static final com.banco.protocolo.LoginResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.LoginResponse();
  }

  public static com.banco.protocolo.LoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginResponse>
      PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
    @java.lang.Override
    public LoginResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoginResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.LoginResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

