// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 tipo = 2;</code>
   * @return The tipo.
   */
  int getTipo();

  /**
   * <code>int32 numeroConta = 3;</code>
   * @return The numeroConta.
   */
  int getNumeroConta();

  /**
   * <code>string nomeTitular = 4;</code>
   * @return The nomeTitular.
   */
  java.lang.String getNomeTitular();
  /**
   * <code>string nomeTitular = 4;</code>
   * @return The bytes for nomeTitular.
   */
  com.google.protobuf.ByteString
      getNomeTitularBytes();

  /**
   * <code>double saldo = 5;</code>
   * @return The saldo.
   */
  double getSaldo();

  /**
   * <code>double limite = 6;</code>
   * @return The limite.
   */
  double getLimite();

  /**
   * <code>double rendimento = 7;</code>
   * @return The rendimento.
   */
  double getRendimento();
}
