// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 numeroConta = 2;</code>
   * @return The numeroConta.
   */
  int getNumeroConta();
}
