// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * <pre>
 * 2
 * </pre>
 *
 * Protobuf type {@code LoginRequest}
 */
@com.google.protobuf.Generated
public final class LoginRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:LoginRequest)
    LoginRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "LoginRequest");
  }
  // Use LoginRequest.newBuilder() to construct.
  private LoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LoginRequest() {
    cpf_ = "";
    senha_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.LoginRequest.class, com.banco.protocolo.LoginRequest.Builder.class);
  }

  public static final int CPF_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cpf_ = "";
  /**
   * <code>string cpf = 1;</code>
   * @return The cpf.
   */
  @java.lang.Override
  public java.lang.String getCpf() {
    java.lang.Object ref = cpf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpf_ = s;
      return s;
    }
  }
  /**
   * <code>string cpf = 1;</code>
   * @return The bytes for cpf.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCpfBytes() {
    java.lang.Object ref = cpf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENHA_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senha_ = "";
  /**
   * <code>string senha = 2;</code>
   * @return The senha.
   */
  @java.lang.Override
  public java.lang.String getSenha() {
    java.lang.Object ref = senha_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senha_ = s;
      return s;
    }
  }
  /**
   * <code>string senha = 2;</code>
   * @return The bytes for senha.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenhaBytes() {
    java.lang.Object ref = senha_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senha_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPO_FIELD_NUMBER = 3;
  private int tipo_ = 0;
  /**
   * <code>int32 tipo = 3;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public int getTipo() {
    return tipo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpf_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, cpf_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senha_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, senha_);
    }
    if (tipo_ != 0) {
      output.writeInt32(3, tipo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpf_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, cpf_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senha_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senha_);
    }
    if (tipo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tipo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.LoginRequest)) {
      return super.equals(obj);
    }
    com.banco.protocolo.LoginRequest other = (com.banco.protocolo.LoginRequest) obj;

    if (!getCpf()
        .equals(other.getCpf())) return false;
    if (!getSenha()
        .equals(other.getSenha())) return false;
    if (getTipo()
        != other.getTipo()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CPF_FIELD_NUMBER;
    hash = (53 * hash) + getCpf().hashCode();
    hash = (37 * hash) + SENHA_FIELD_NUMBER;
    hash = (53 * hash) + getSenha().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.LoginRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.LoginRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.LoginRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.LoginRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 2
   * </pre>
   *
   * Protobuf type {@code LoginRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LoginRequest)
      com.banco.protocolo.LoginRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.LoginRequest.class, com.banco.protocolo.LoginRequest.Builder.class);
    }

    // Construct using com.banco.protocolo.LoginRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cpf_ = "";
      senha_ = "";
      tipo_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_LoginRequest_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.LoginRequest getDefaultInstanceForType() {
      return com.banco.protocolo.LoginRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.LoginRequest build() {
      com.banco.protocolo.LoginRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.LoginRequest buildPartial() {
      com.banco.protocolo.LoginRequest result = new com.banco.protocolo.LoginRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.LoginRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cpf_ = cpf_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.senha_ = senha_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tipo_ = tipo_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.LoginRequest) {
        return mergeFrom((com.banco.protocolo.LoginRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.LoginRequest other) {
      if (other == com.banco.protocolo.LoginRequest.getDefaultInstance()) return this;
      if (!other.getCpf().isEmpty()) {
        cpf_ = other.cpf_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSenha().isEmpty()) {
        senha_ = other.senha_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTipo() != 0) {
        setTipo(other.getTipo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cpf_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              senha_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tipo_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object cpf_ = "";
    /**
     * <code>string cpf = 1;</code>
     * @return The cpf.
     */
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cpf = 1;</code>
     * @return The bytes for cpf.
     */
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cpf = 1;</code>
     * @param value The cpf to set.
     * @return This builder for chaining.
     */
    public Builder setCpf(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cpf_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string cpf = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpf() {
      cpf_ = getDefaultInstance().getCpf();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string cpf = 1;</code>
     * @param value The bytes for cpf to set.
     * @return This builder for chaining.
     */
    public Builder setCpfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cpf_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object senha_ = "";
    /**
     * <code>string senha = 2;</code>
     * @return The senha.
     */
    public java.lang.String getSenha() {
      java.lang.Object ref = senha_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senha_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senha = 2;</code>
     * @return The bytes for senha.
     */
    public com.google.protobuf.ByteString
        getSenhaBytes() {
      java.lang.Object ref = senha_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senha = 2;</code>
     * @param value The senha to set.
     * @return This builder for chaining.
     */
    public Builder setSenha(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senha_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string senha = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenha() {
      senha_ = getDefaultInstance().getSenha();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string senha = 2;</code>
     * @param value The bytes for senha to set.
     * @return This builder for chaining.
     */
    public Builder setSenhaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senha_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int tipo_ ;
    /**
     * <code>int32 tipo = 3;</code>
     * @return The tipo.
     */
    @java.lang.Override
    public int getTipo() {
      return tipo_;
    }
    /**
     * <code>int32 tipo = 3;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(int value) {

      tipo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tipo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tipo_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:LoginRequest)
  }

  // @@protoc_insertion_point(class_scope:LoginRequest)
  private static final com.banco.protocolo.LoginRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.LoginRequest();
  }

  public static com.banco.protocolo.LoginRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginRequest>
      PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
    @java.lang.Override
    public LoginRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LoginRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.LoginRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

