// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface MensagemRMIOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MensagemRMI)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>int32 requestId = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>string objectReference = 3;</code>
   * @return The objectReference.
   */
  java.lang.String getObjectReference();
  /**
   * <code>string objectReference = 3;</code>
   * @return The bytes for objectReference.
   */
  com.google.protobuf.ByteString
      getObjectReferenceBytes();

  /**
   * <code>string methodId = 4;</code>
   * @return The methodId.
   */
  java.lang.String getMethodId();
  /**
   * <code>string methodId = 4;</code>
   * @return The bytes for methodId.
   */
  com.google.protobuf.ByteString
      getMethodIdBytes();

  /**
   * <code>bytes arguments = 5;</code>
   * @return The arguments.
   */
  com.google.protobuf.ByteString getArguments();
}
