// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * Protobuf type {@code MensagemRMI}
 */
@com.google.protobuf.Generated
public final class MensagemRMI extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:MensagemRMI)
    MensagemRMIOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MensagemRMI");
  }
  // Use MensagemRMI.newBuilder() to construct.
  private MensagemRMI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MensagemRMI() {
    objectReference_ = "";
    methodId_ = "";
    arguments_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.MensagemRMI.class, com.banco.protocolo.MensagemRMI.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_ = 0;
  /**
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  public static final int REQUESTID_FIELD_NUMBER = 2;
  private int requestId_ = 0;
  /**
   * <code>int32 requestId = 2;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public int getRequestId() {
    return requestId_;
  }

  public static final int OBJECTREFERENCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectReference_ = "";
  /**
   * <code>string objectReference = 3;</code>
   * @return The objectReference.
   */
  @java.lang.Override
  public java.lang.String getObjectReference() {
    java.lang.Object ref = objectReference_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectReference_ = s;
      return s;
    }
  }
  /**
   * <code>string objectReference = 3;</code>
   * @return The bytes for objectReference.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectReferenceBytes() {
    java.lang.Object ref = objectReference_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object methodId_ = "";
  /**
   * <code>string methodId = 4;</code>
   * @return The methodId.
   */
  @java.lang.Override
  public java.lang.String getMethodId() {
    java.lang.Object ref = methodId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodId_ = s;
      return s;
    }
  }
  /**
   * <code>string methodId = 4;</code>
   * @return The bytes for methodId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodIdBytes() {
    java.lang.Object ref = methodId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGUMENTS_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString arguments_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes arguments = 5;</code>
   * @return The arguments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getArguments() {
    return arguments_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != 0) {
      output.writeInt32(1, messageType_);
    }
    if (requestId_ != 0) {
      output.writeInt32(2, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectReference_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, objectReference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, methodId_);
    }
    if (!arguments_.isEmpty()) {
      output.writeBytes(5, arguments_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, messageType_);
    }
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectReference_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, objectReference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, methodId_);
    }
    if (!arguments_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, arguments_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.MensagemRMI)) {
      return super.equals(obj);
    }
    com.banco.protocolo.MensagemRMI other = (com.banco.protocolo.MensagemRMI) obj;

    if (getMessageType()
        != other.getMessageType()) return false;
    if (getRequestId()
        != other.getRequestId()) return false;
    if (!getObjectReference()
        .equals(other.getObjectReference())) return false;
    if (!getMethodId()
        .equals(other.getMethodId())) return false;
    if (!getArguments()
        .equals(other.getArguments())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    hash = (37 * hash) + OBJECTREFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getObjectReference().hashCode();
    hash = (37 * hash) + METHODID_FIELD_NUMBER;
    hash = (53 * hash) + getMethodId().hashCode();
    hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getArguments().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.MensagemRMI parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.MensagemRMI parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.MensagemRMI parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.MensagemRMI parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.MensagemRMI prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MensagemRMI}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MensagemRMI)
      com.banco.protocolo.MensagemRMIOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.MensagemRMI.class, com.banco.protocolo.MensagemRMI.Builder.class);
    }

    // Construct using com.banco.protocolo.MensagemRMI.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageType_ = 0;
      requestId_ = 0;
      objectReference_ = "";
      methodId_ = "";
      arguments_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_MensagemRMI_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.MensagemRMI getDefaultInstanceForType() {
      return com.banco.protocolo.MensagemRMI.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.MensagemRMI build() {
      com.banco.protocolo.MensagemRMI result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.MensagemRMI buildPartial() {
      com.banco.protocolo.MensagemRMI result = new com.banco.protocolo.MensagemRMI(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.MensagemRMI result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageType_ = messageType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.objectReference_ = objectReference_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.methodId_ = methodId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.arguments_ = arguments_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.MensagemRMI) {
        return mergeFrom((com.banco.protocolo.MensagemRMI)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.MensagemRMI other) {
      if (other == com.banco.protocolo.MensagemRMI.getDefaultInstance()) return this;
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      if (!other.getObjectReference().isEmpty()) {
        objectReference_ = other.objectReference_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMethodId().isEmpty()) {
        methodId_ = other.methodId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getArguments().isEmpty()) {
        setArguments(other.getArguments());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageType_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              requestId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              objectReference_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              methodId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              arguments_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int messageType_ ;
    /**
     * <code>int32 messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <code>int32 messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {

      messageType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private int requestId_ ;
    /**
     * <code>int32 requestId = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 requestId = 2;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(int value) {

      requestId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 requestId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object objectReference_ = "";
    /**
     * <code>string objectReference = 3;</code>
     * @return The objectReference.
     */
    public java.lang.String getObjectReference() {
      java.lang.Object ref = objectReference_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectReference_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string objectReference = 3;</code>
     * @return The bytes for objectReference.
     */
    public com.google.protobuf.ByteString
        getObjectReferenceBytes() {
      java.lang.Object ref = objectReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string objectReference = 3;</code>
     * @param value The objectReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjectReference(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectReference_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string objectReference = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectReference() {
      objectReference_ = getDefaultInstance().getObjectReference();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string objectReference = 3;</code>
     * @param value The bytes for objectReference to set.
     * @return This builder for chaining.
     */
    public Builder setObjectReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectReference_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object methodId_ = "";
    /**
     * <code>string methodId = 4;</code>
     * @return The methodId.
     */
    public java.lang.String getMethodId() {
      java.lang.Object ref = methodId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string methodId = 4;</code>
     * @return The bytes for methodId.
     */
    public com.google.protobuf.ByteString
        getMethodIdBytes() {
      java.lang.Object ref = methodId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string methodId = 4;</code>
     * @param value The methodId to set.
     * @return This builder for chaining.
     */
    public Builder setMethodId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      methodId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string methodId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodId() {
      methodId_ = getDefaultInstance().getMethodId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string methodId = 4;</code>
     * @param value The bytes for methodId to set.
     * @return This builder for chaining.
     */
    public Builder setMethodIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      methodId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString arguments_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes arguments = 5;</code>
     * @return The arguments.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getArguments() {
      return arguments_;
    }
    /**
     * <code>bytes arguments = 5;</code>
     * @param value The arguments to set.
     * @return This builder for chaining.
     */
    public Builder setArguments(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      arguments_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes arguments = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArguments() {
      bitField0_ = (bitField0_ & ~0x00000010);
      arguments_ = getDefaultInstance().getArguments();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:MensagemRMI)
  }

  // @@protoc_insertion_point(class_scope:MensagemRMI)
  private static final com.banco.protocolo.MensagemRMI DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.MensagemRMI();
  }

  public static com.banco.protocolo.MensagemRMI getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MensagemRMI>
      PARSER = new com.google.protobuf.AbstractParser<MensagemRMI>() {
    @java.lang.Override
    public MensagemRMI parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MensagemRMI> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MensagemRMI> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.MensagemRMI getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

