// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public final class MensagemProtocolo extends com.google.protobuf.GeneratedFile {
  private MensagemProtocolo() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MensagemProtocolo");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MensagemRMI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MensagemRMI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CadastroRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CadastroRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SacarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SacarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DepositoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DepositoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransferirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PagarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PagarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProjetarRendimentoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProjetarRendimentoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExtratoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExtratoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransferirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransferirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RendimentoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RendimentoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExtratoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExtratoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/MensagemRMI.proto\"s\n\013MensagemRMI" +
      "\022\023\n\013messageType\030\001 \001(\005\022\021\n\trequestId\030\002 \001(\005" +
      "\022\027\n\017objectReference\030\003 \001(\t\022\020\n\010methodId\030\004 " +
      "\001(\t\022\021\n\targuments\030\005 \001(\014\"I\n\017CadastroReques" +
      "t\022\014\n\004nome\030\001 \001(\t\022\013\n\003cpf\030\002 \001(\t\022\r\n\005senha\030\003 " +
      "\001(\t\022\014\n\004tipo\030\004 \001(\005\"8\n\014LoginRequest\022\013\n\003cpf" +
      "\030\001 \001(\t\022\r\n\005senha\030\002 \001(\t\022\014\n\004tipo\030\003 \001(\005\"7\n\014S" +
      "acarRequest\022\023\n\013numeroSaque\030\001 \001(\005\022\022\n\nvalo" +
      "rSaque\030\002 \001(\001\"@\n\017DepositoRequest\022\026\n\016numer" +
      "oDeposito\030\001 \001(\005\022\025\n\rvalorDeposito\030\002 \001(\001\"I" +
      "\n\021TransferirRequest\022\021\n\tnumOrigem\030\001 \001(\005\022\022" +
      "\n\nnumDestino\030\002 \001(\005\022\r\n\005valor\030\003 \001(\001\"H\n\014Pag" +
      "arRequest\022\023\n\013numContaPag\030\001 \001(\005\022\020\n\010valorP" +
      "ag\030\002 \001(\001\022\021\n\tdescricao\030\003 \001(\t\"D\n\031ProjetarR" +
      "endimentoRequest\022\030\n\020numeroRendimento\030\001 \001" +
      "(\005\022\r\n\005meses\030\002 \001(\005\")\n\016ExtratoRequest\022\027\n\017n" +
      "umContaExtrato\030\001 \001(\005\" \n\016StatusResponse\022\016" +
      "\n\006status\030\001 \001(\005\"\212\001\n\rLoginResponse\022\016\n\006stat" +
      "us\030\001 \001(\005\022\014\n\004tipo\030\002 \001(\005\022\023\n\013numeroConta\030\003 " +
      "\001(\005\022\023\n\013nomeTitular\030\004 \001(\t\022\r\n\005saldo\030\005 \001(\001\022" +
      "\016\n\006limite\030\006 \001(\001\022\022\n\nrendimento\030\007 \001(\001\"9\n\022T" +
      "ransferirResponse\022\016\n\006status\030\001 \001(\005\022\023\n\013nom" +
      "eDestino\030\002 \001(\t\"<\n\022RendimentoResponse\022\016\n\006" +
      "status\030\001 \001(\005\022\026\n\016valorResultado\030\002 \001(\001\"1\n\017" +
      "ExtratoResponse\022\016\n\006status\030\001 \001(\005\022\016\n\006linha" +
      "s\030\002 \003(\tB*\n\023com.banco.protocoloB\021Mensagem" +
      "ProtocoloP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MensagemRMI_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_MensagemRMI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MensagemRMI_descriptor,
        new java.lang.String[] { "MessageType", "RequestId", "ObjectReference", "MethodId", "Arguments", });
    internal_static_CadastroRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_CadastroRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CadastroRequest_descriptor,
        new java.lang.String[] { "Nome", "Cpf", "Senha", "Tipo", });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "Cpf", "Senha", "Tipo", });
    internal_static_SacarRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_SacarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SacarRequest_descriptor,
        new java.lang.String[] { "NumeroSaque", "ValorSaque", });
    internal_static_DepositoRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_DepositoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DepositoRequest_descriptor,
        new java.lang.String[] { "NumeroDeposito", "ValorDeposito", });
    internal_static_TransferirRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_TransferirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransferirRequest_descriptor,
        new java.lang.String[] { "NumOrigem", "NumDestino", "Valor", });
    internal_static_PagarRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_PagarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PagarRequest_descriptor,
        new java.lang.String[] { "NumContaPag", "ValorPag", "Descricao", });
    internal_static_ProjetarRendimentoRequest_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_ProjetarRendimentoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProjetarRendimentoRequest_descriptor,
        new java.lang.String[] { "NumeroRendimento", "Meses", });
    internal_static_ExtratoRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_ExtratoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ExtratoRequest_descriptor,
        new java.lang.String[] { "NumContaExtrato", });
    internal_static_StatusResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Status", "Tipo", "NumeroConta", "NomeTitular", "Saldo", "Limite", "Rendimento", });
    internal_static_TransferirResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_TransferirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransferirResponse_descriptor,
        new java.lang.String[] { "Status", "NomeDestino", });
    internal_static_RendimentoResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_RendimentoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RendimentoResponse_descriptor,
        new java.lang.String[] { "Status", "ValorResultado", });
    internal_static_ExtratoResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_ExtratoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ExtratoResponse_descriptor,
        new java.lang.String[] { "Status", "Linhas", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
