// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * <pre>
 * 6
 * </pre>
 *
 * Protobuf type {@code PagarRequest}
 */
@com.google.protobuf.Generated
public final class PagarRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PagarRequest)
    PagarRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PagarRequest");
  }
  // Use PagarRequest.newBuilder() to construct.
  private PagarRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PagarRequest() {
    descricao_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.PagarRequest.class, com.banco.protocolo.PagarRequest.Builder.class);
  }

  public static final int NUMCONTAPAG_FIELD_NUMBER = 1;
  private int numContaPag_ = 0;
  /**
   * <code>int32 numContaPag = 1;</code>
   * @return The numContaPag.
   */
  @java.lang.Override
  public int getNumContaPag() {
    return numContaPag_;
  }

  public static final int VALORPAG_FIELD_NUMBER = 2;
  private double valorPag_ = 0D;
  /**
   * <code>double valorPag = 2;</code>
   * @return The valorPag.
   */
  @java.lang.Override
  public double getValorPag() {
    return valorPag_;
  }

  public static final int DESCRICAO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object descricao_ = "";
  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  @java.lang.Override
  public java.lang.String getDescricao() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descricao_ = s;
      return s;
    }
  }
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescricaoBytes() {
    java.lang.Object ref = descricao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descricao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numContaPag_ != 0) {
      output.writeInt32(1, numContaPag_);
    }
    if (java.lang.Double.doubleToRawLongBits(valorPag_) != 0) {
      output.writeDouble(2, valorPag_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, descricao_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numContaPag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numContaPag_);
    }
    if (java.lang.Double.doubleToRawLongBits(valorPag_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, valorPag_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(descricao_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, descricao_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.PagarRequest)) {
      return super.equals(obj);
    }
    com.banco.protocolo.PagarRequest other = (com.banco.protocolo.PagarRequest) obj;

    if (getNumContaPag()
        != other.getNumContaPag()) return false;
    if (java.lang.Double.doubleToLongBits(getValorPag())
        != java.lang.Double.doubleToLongBits(
            other.getValorPag())) return false;
    if (!getDescricao()
        .equals(other.getDescricao())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMCONTAPAG_FIELD_NUMBER;
    hash = (53 * hash) + getNumContaPag();
    hash = (37 * hash) + VALORPAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValorPag()));
    hash = (37 * hash) + DESCRICAO_FIELD_NUMBER;
    hash = (53 * hash) + getDescricao().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.PagarRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.PagarRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.PagarRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.PagarRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.PagarRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 6
   * </pre>
   *
   * Protobuf type {@code PagarRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PagarRequest)
      com.banco.protocolo.PagarRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.PagarRequest.class, com.banco.protocolo.PagarRequest.Builder.class);
    }

    // Construct using com.banco.protocolo.PagarRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numContaPag_ = 0;
      valorPag_ = 0D;
      descricao_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_PagarRequest_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.PagarRequest getDefaultInstanceForType() {
      return com.banco.protocolo.PagarRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.PagarRequest build() {
      com.banco.protocolo.PagarRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.PagarRequest buildPartial() {
      com.banco.protocolo.PagarRequest result = new com.banco.protocolo.PagarRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.PagarRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numContaPag_ = numContaPag_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.valorPag_ = valorPag_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.descricao_ = descricao_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.PagarRequest) {
        return mergeFrom((com.banco.protocolo.PagarRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.PagarRequest other) {
      if (other == com.banco.protocolo.PagarRequest.getDefaultInstance()) return this;
      if (other.getNumContaPag() != 0) {
        setNumContaPag(other.getNumContaPag());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getValorPag()) != 0) {
        setValorPag(other.getValorPag());
      }
      if (!other.getDescricao().isEmpty()) {
        descricao_ = other.descricao_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numContaPag_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              valorPag_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              descricao_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int numContaPag_ ;
    /**
     * <code>int32 numContaPag = 1;</code>
     * @return The numContaPag.
     */
    @java.lang.Override
    public int getNumContaPag() {
      return numContaPag_;
    }
    /**
     * <code>int32 numContaPag = 1;</code>
     * @param value The numContaPag to set.
     * @return This builder for chaining.
     */
    public Builder setNumContaPag(int value) {

      numContaPag_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numContaPag = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumContaPag() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numContaPag_ = 0;
      onChanged();
      return this;
    }

    private double valorPag_ ;
    /**
     * <code>double valorPag = 2;</code>
     * @return The valorPag.
     */
    @java.lang.Override
    public double getValorPag() {
      return valorPag_;
    }
    /**
     * <code>double valorPag = 2;</code>
     * @param value The valorPag to set.
     * @return This builder for chaining.
     */
    public Builder setValorPag(double value) {

      valorPag_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double valorPag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValorPag() {
      bitField0_ = (bitField0_ & ~0x00000002);
      valorPag_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object descricao_ = "";
    /**
     * <code>string descricao = 3;</code>
     * @return The descricao.
     */
    public java.lang.String getDescricao() {
      java.lang.Object ref = descricao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descricao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @return The bytes for descricao.
     */
    public com.google.protobuf.ByteString
        getDescricaoBytes() {
      java.lang.Object ref = descricao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricao(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescricao() {
      descricao_ = getDefaultInstance().getDescricao();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string descricao = 3;</code>
     * @param value The bytes for descricao to set.
     * @return This builder for chaining.
     */
    public Builder setDescricaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      descricao_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PagarRequest)
  }

  // @@protoc_insertion_point(class_scope:PagarRequest)
  private static final com.banco.protocolo.PagarRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.PagarRequest();
  }

  public static com.banco.protocolo.PagarRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PagarRequest>
      PARSER = new com.google.protobuf.AbstractParser<PagarRequest>() {
    @java.lang.Override
    public PagarRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PagarRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PagarRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.PagarRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

