// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface PagarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PagarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numContaPag = 1;</code>
   * @return The numContaPag.
   */
  int getNumContaPag();

  /**
   * <code>double valorPag = 2;</code>
   * @return The valorPag.
   */
  double getValorPag();

  /**
   * <code>string descricao = 3;</code>
   * @return The descricao.
   */
  java.lang.String getDescricao();
  /**
   * <code>string descricao = 3;</code>
   * @return The bytes for descricao.
   */
  com.google.protobuf.ByteString
      getDescricaoBytes();
}
