// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * <pre>
 * 7
 * </pre>
 *
 * Protobuf type {@code ProjetarRendimentoRequest}
 */
@com.google.protobuf.Generated
public final class ProjetarRendimentoRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ProjetarRendimentoRequest)
    ProjetarRendimentoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ProjetarRendimentoRequest");
  }
  // Use ProjetarRendimentoRequest.newBuilder() to construct.
  private ProjetarRendimentoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProjetarRendimentoRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.ProjetarRendimentoRequest.class, com.banco.protocolo.ProjetarRendimentoRequest.Builder.class);
  }

  public static final int NUMERORENDIMENTO_FIELD_NUMBER = 1;
  private int numeroRendimento_ = 0;
  /**
   * <code>int32 numeroRendimento = 1;</code>
   * @return The numeroRendimento.
   */
  @java.lang.Override
  public int getNumeroRendimento() {
    return numeroRendimento_;
  }

  public static final int MESES_FIELD_NUMBER = 2;
  private int meses_ = 0;
  /**
   * <code>int32 meses = 2;</code>
   * @return The meses.
   */
  @java.lang.Override
  public int getMeses() {
    return meses_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numeroRendimento_ != 0) {
      output.writeInt32(1, numeroRendimento_);
    }
    if (meses_ != 0) {
      output.writeInt32(2, meses_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numeroRendimento_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numeroRendimento_);
    }
    if (meses_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, meses_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.ProjetarRendimentoRequest)) {
      return super.equals(obj);
    }
    com.banco.protocolo.ProjetarRendimentoRequest other = (com.banco.protocolo.ProjetarRendimentoRequest) obj;

    if (getNumeroRendimento()
        != other.getNumeroRendimento()) return false;
    if (getMeses()
        != other.getMeses()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMERORENDIMENTO_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroRendimento();
    hash = (37 * hash) + MESES_FIELD_NUMBER;
    hash = (53 * hash) + getMeses();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.ProjetarRendimentoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.ProjetarRendimentoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.ProjetarRendimentoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.ProjetarRendimentoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 7
   * </pre>
   *
   * Protobuf type {@code ProjetarRendimentoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProjetarRendimentoRequest)
      com.banco.protocolo.ProjetarRendimentoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.ProjetarRendimentoRequest.class, com.banco.protocolo.ProjetarRendimentoRequest.Builder.class);
    }

    // Construct using com.banco.protocolo.ProjetarRendimentoRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numeroRendimento_ = 0;
      meses_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_ProjetarRendimentoRequest_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.ProjetarRendimentoRequest getDefaultInstanceForType() {
      return com.banco.protocolo.ProjetarRendimentoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.ProjetarRendimentoRequest build() {
      com.banco.protocolo.ProjetarRendimentoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.ProjetarRendimentoRequest buildPartial() {
      com.banco.protocolo.ProjetarRendimentoRequest result = new com.banco.protocolo.ProjetarRendimentoRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.ProjetarRendimentoRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numeroRendimento_ = numeroRendimento_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.meses_ = meses_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.ProjetarRendimentoRequest) {
        return mergeFrom((com.banco.protocolo.ProjetarRendimentoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.ProjetarRendimentoRequest other) {
      if (other == com.banco.protocolo.ProjetarRendimentoRequest.getDefaultInstance()) return this;
      if (other.getNumeroRendimento() != 0) {
        setNumeroRendimento(other.getNumeroRendimento());
      }
      if (other.getMeses() != 0) {
        setMeses(other.getMeses());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numeroRendimento_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              meses_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int numeroRendimento_ ;
    /**
     * <code>int32 numeroRendimento = 1;</code>
     * @return The numeroRendimento.
     */
    @java.lang.Override
    public int getNumeroRendimento() {
      return numeroRendimento_;
    }
    /**
     * <code>int32 numeroRendimento = 1;</code>
     * @param value The numeroRendimento to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroRendimento(int value) {

      numeroRendimento_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numeroRendimento = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroRendimento() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numeroRendimento_ = 0;
      onChanged();
      return this;
    }

    private int meses_ ;
    /**
     * <code>int32 meses = 2;</code>
     * @return The meses.
     */
    @java.lang.Override
    public int getMeses() {
      return meses_;
    }
    /**
     * <code>int32 meses = 2;</code>
     * @param value The meses to set.
     * @return This builder for chaining.
     */
    public Builder setMeses(int value) {

      meses_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 meses = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeses() {
      bitField0_ = (bitField0_ & ~0x00000002);
      meses_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ProjetarRendimentoRequest)
  }

  // @@protoc_insertion_point(class_scope:ProjetarRendimentoRequest)
  private static final com.banco.protocolo.ProjetarRendimentoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.ProjetarRendimentoRequest();
  }

  public static com.banco.protocolo.ProjetarRendimentoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProjetarRendimentoRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProjetarRendimentoRequest>() {
    @java.lang.Override
    public ProjetarRendimentoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProjetarRendimentoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProjetarRendimentoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.ProjetarRendimentoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

