// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface ProjetarRendimentoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProjetarRendimentoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numeroRendimento = 1;</code>
   * @return The numeroRendimento.
   */
  int getNumeroRendimento();

  /**
   * <code>int32 meses = 2;</code>
   * @return The meses.
   */
  int getMeses();
}
