// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface RendimentoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RendimentoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>double valorResultado = 2;</code>
   * @return The valorResultado.
   */
  double getValorResultado();
}
