// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface SacarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SacarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numeroSaque = 1;</code>
   * @return The numeroSaque.
   */
  int getNumeroSaque();

  /**
   * <code>double valorSaque = 2;</code>
   * @return The valorSaque.
   */
  double getValorSaque();
}
