// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * <pre>
 * 3
 * </pre>
 *
 * Protobuf type {@code SacarRequest}
 */
@com.google.protobuf.Generated
public final class SacarRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SacarRequest)
    SacarRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "SacarRequest");
  }
  // Use SacarRequest.newBuilder() to construct.
  private SacarRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SacarRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.SacarRequest.class, com.banco.protocolo.SacarRequest.Builder.class);
  }

  public static final int NUMEROSAQUE_FIELD_NUMBER = 1;
  private int numeroSaque_ = 0;
  /**
   * <code>int32 numeroSaque = 1;</code>
   * @return The numeroSaque.
   */
  @java.lang.Override
  public int getNumeroSaque() {
    return numeroSaque_;
  }

  public static final int VALORSAQUE_FIELD_NUMBER = 2;
  private double valorSaque_ = 0D;
  /**
   * <code>double valorSaque = 2;</code>
   * @return The valorSaque.
   */
  @java.lang.Override
  public double getValorSaque() {
    return valorSaque_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numeroSaque_ != 0) {
      output.writeInt32(1, numeroSaque_);
    }
    if (java.lang.Double.doubleToRawLongBits(valorSaque_) != 0) {
      output.writeDouble(2, valorSaque_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numeroSaque_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numeroSaque_);
    }
    if (java.lang.Double.doubleToRawLongBits(valorSaque_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, valorSaque_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.SacarRequest)) {
      return super.equals(obj);
    }
    com.banco.protocolo.SacarRequest other = (com.banco.protocolo.SacarRequest) obj;

    if (getNumeroSaque()
        != other.getNumeroSaque()) return false;
    if (java.lang.Double.doubleToLongBits(getValorSaque())
        != java.lang.Double.doubleToLongBits(
            other.getValorSaque())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMEROSAQUE_FIELD_NUMBER;
    hash = (53 * hash) + getNumeroSaque();
    hash = (37 * hash) + VALORSAQUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValorSaque()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.SacarRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.SacarRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.SacarRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.SacarRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.SacarRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 3
   * </pre>
   *
   * Protobuf type {@code SacarRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SacarRequest)
      com.banco.protocolo.SacarRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.SacarRequest.class, com.banco.protocolo.SacarRequest.Builder.class);
    }

    // Construct using com.banco.protocolo.SacarRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numeroSaque_ = 0;
      valorSaque_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_SacarRequest_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.SacarRequest getDefaultInstanceForType() {
      return com.banco.protocolo.SacarRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.SacarRequest build() {
      com.banco.protocolo.SacarRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.SacarRequest buildPartial() {
      com.banco.protocolo.SacarRequest result = new com.banco.protocolo.SacarRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.SacarRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numeroSaque_ = numeroSaque_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.valorSaque_ = valorSaque_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.SacarRequest) {
        return mergeFrom((com.banco.protocolo.SacarRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.SacarRequest other) {
      if (other == com.banco.protocolo.SacarRequest.getDefaultInstance()) return this;
      if (other.getNumeroSaque() != 0) {
        setNumeroSaque(other.getNumeroSaque());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getValorSaque()) != 0) {
        setValorSaque(other.getValorSaque());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numeroSaque_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              valorSaque_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int numeroSaque_ ;
    /**
     * <code>int32 numeroSaque = 1;</code>
     * @return The numeroSaque.
     */
    @java.lang.Override
    public int getNumeroSaque() {
      return numeroSaque_;
    }
    /**
     * <code>int32 numeroSaque = 1;</code>
     * @param value The numeroSaque to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroSaque(int value) {

      numeroSaque_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numeroSaque = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumeroSaque() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numeroSaque_ = 0;
      onChanged();
      return this;
    }

    private double valorSaque_ ;
    /**
     * <code>double valorSaque = 2;</code>
     * @return The valorSaque.
     */
    @java.lang.Override
    public double getValorSaque() {
      return valorSaque_;
    }
    /**
     * <code>double valorSaque = 2;</code>
     * @param value The valorSaque to set.
     * @return This builder for chaining.
     */
    public Builder setValorSaque(double value) {

      valorSaque_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double valorSaque = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValorSaque() {
      bitField0_ = (bitField0_ & ~0x00000002);
      valorSaque_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SacarRequest)
  }

  // @@protoc_insertion_point(class_scope:SacarRequest)
  private static final com.banco.protocolo.SacarRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.SacarRequest();
  }

  public static com.banco.protocolo.SacarRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SacarRequest>
      PARSER = new com.google.protobuf.AbstractParser<SacarRequest>() {
    @java.lang.Override
    public SacarRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SacarRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SacarRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.SacarRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

