// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface TransferirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransferirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numOrigem = 1;</code>
   * @return The numOrigem.
   */
  int getNumOrigem();

  /**
   * <code>int32 numDestino = 2;</code>
   * @return The numDestino.
   */
  int getNumDestino();

  /**
   * <code>double valor = 3;</code>
   * @return The valor.
   */
  double getValor();
}
