// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

@com.google.protobuf.Generated
public interface TransferirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransferirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string nomeDestino = 2;</code>
   * @return The nomeDestino.
   */
  java.lang.String getNomeDestino();
  /**
   * <code>string nomeDestino = 2;</code>
   * @return The bytes for nomeDestino.
   */
  com.google.protobuf.ByteString
      getNomeDestinoBytes();
}
