// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/MensagemRMI.proto
// Protobuf Java Version: 4.34.1

package com.banco.protocolo;

/**
 * <pre>
 * 5
 * </pre>
 *
 * Protobuf type {@code TransferirRequest}
 */
@com.google.protobuf.Generated
public final class TransferirRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TransferirRequest)
    TransferirRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TransferirRequest");
  }
  // Use TransferirRequest.newBuilder() to construct.
  private TransferirRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransferirRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banco.protocolo.TransferirRequest.class, com.banco.protocolo.TransferirRequest.Builder.class);
  }

  public static final int NUMORIGEM_FIELD_NUMBER = 1;
  private int numOrigem_ = 0;
  /**
   * <code>int32 numOrigem = 1;</code>
   * @return The numOrigem.
   */
  @java.lang.Override
  public int getNumOrigem() {
    return numOrigem_;
  }

  public static final int NUMDESTINO_FIELD_NUMBER = 2;
  private int numDestino_ = 0;
  /**
   * <code>int32 numDestino = 2;</code>
   * @return The numDestino.
   */
  @java.lang.Override
  public int getNumDestino() {
    return numDestino_;
  }

  public static final int VALOR_FIELD_NUMBER = 3;
  private double valor_ = 0D;
  /**
   * <code>double valor = 3;</code>
   * @return The valor.
   */
  @java.lang.Override
  public double getValor() {
    return valor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numOrigem_ != 0) {
      output.writeInt32(1, numOrigem_);
    }
    if (numDestino_ != 0) {
      output.writeInt32(2, numDestino_);
    }
    if (java.lang.Double.doubleToRawLongBits(valor_) != 0) {
      output.writeDouble(3, valor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numOrigem_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numOrigem_);
    }
    if (numDestino_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numDestino_);
    }
    if (java.lang.Double.doubleToRawLongBits(valor_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, valor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banco.protocolo.TransferirRequest)) {
      return super.equals(obj);
    }
    com.banco.protocolo.TransferirRequest other = (com.banco.protocolo.TransferirRequest) obj;

    if (getNumOrigem()
        != other.getNumOrigem()) return false;
    if (getNumDestino()
        != other.getNumDestino()) return false;
    if (java.lang.Double.doubleToLongBits(getValor())
        != java.lang.Double.doubleToLongBits(
            other.getValor())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMORIGEM_FIELD_NUMBER;
    hash = (53 * hash) + getNumOrigem();
    hash = (37 * hash) + NUMDESTINO_FIELD_NUMBER;
    hash = (53 * hash) + getNumDestino();
    hash = (37 * hash) + VALOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValor()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banco.protocolo.TransferirRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.banco.protocolo.TransferirRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.banco.protocolo.TransferirRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.banco.protocolo.TransferirRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banco.protocolo.TransferirRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 5
   * </pre>
   *
   * Protobuf type {@code TransferirRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransferirRequest)
      com.banco.protocolo.TransferirRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banco.protocolo.TransferirRequest.class, com.banco.protocolo.TransferirRequest.Builder.class);
    }

    // Construct using com.banco.protocolo.TransferirRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numOrigem_ = 0;
      numDestino_ = 0;
      valor_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banco.protocolo.MensagemProtocolo.internal_static_TransferirRequest_descriptor;
    }

    @java.lang.Override
    public com.banco.protocolo.TransferirRequest getDefaultInstanceForType() {
      return com.banco.protocolo.TransferirRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banco.protocolo.TransferirRequest build() {
      com.banco.protocolo.TransferirRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banco.protocolo.TransferirRequest buildPartial() {
      com.banco.protocolo.TransferirRequest result = new com.banco.protocolo.TransferirRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.banco.protocolo.TransferirRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numOrigem_ = numOrigem_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.numDestino_ = numDestino_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.valor_ = valor_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banco.protocolo.TransferirRequest) {
        return mergeFrom((com.banco.protocolo.TransferirRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banco.protocolo.TransferirRequest other) {
      if (other == com.banco.protocolo.TransferirRequest.getDefaultInstance()) return this;
      if (other.getNumOrigem() != 0) {
        setNumOrigem(other.getNumOrigem());
      }
      if (other.getNumDestino() != 0) {
        setNumDestino(other.getNumDestino());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getValor()) != 0) {
        setValor(other.getValor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numOrigem_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              numDestino_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              valor_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int numOrigem_ ;
    /**
     * <code>int32 numOrigem = 1;</code>
     * @return The numOrigem.
     */
    @java.lang.Override
    public int getNumOrigem() {
      return numOrigem_;
    }
    /**
     * <code>int32 numOrigem = 1;</code>
     * @param value The numOrigem to set.
     * @return This builder for chaining.
     */
    public Builder setNumOrigem(int value) {

      numOrigem_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numOrigem = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumOrigem() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numOrigem_ = 0;
      onChanged();
      return this;
    }

    private int numDestino_ ;
    /**
     * <code>int32 numDestino = 2;</code>
     * @return The numDestino.
     */
    @java.lang.Override
    public int getNumDestino() {
      return numDestino_;
    }
    /**
     * <code>int32 numDestino = 2;</code>
     * @param value The numDestino to set.
     * @return This builder for chaining.
     */
    public Builder setNumDestino(int value) {

      numDestino_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numDestino = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumDestino() {
      bitField0_ = (bitField0_ & ~0x00000002);
      numDestino_ = 0;
      onChanged();
      return this;
    }

    private double valor_ ;
    /**
     * <code>double valor = 3;</code>
     * @return The valor.
     */
    @java.lang.Override
    public double getValor() {
      return valor_;
    }
    /**
     * <code>double valor = 3;</code>
     * @param value The valor to set.
     * @return This builder for chaining.
     */
    public Builder setValor(double value) {

      valor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double valor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      valor_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TransferirRequest)
  }

  // @@protoc_insertion_point(class_scope:TransferirRequest)
  private static final com.banco.protocolo.TransferirRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banco.protocolo.TransferirRequest();
  }

  public static com.banco.protocolo.TransferirRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransferirRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransferirRequest>() {
    @java.lang.Override
    public TransferirRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransferirRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransferirRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banco.protocolo.TransferirRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

